### ISSUE TITLE
Error theme generation fails with sublime-color-schemes.

### ISSUE THREAD

**Issue by deathaxe** [divmain/GitSavvy#1029]
GitSavvy uses python's json decoder to load sublime-color-schemes rather than `sublime.load_resource()`, which causes the theme generator to fail, if the color scheme contains comments or trailing commas.

_Note: Python's json library is not a proper solution to handle sublime resource files at all as it is too restrictive._

**Steps to reproduce**

1. Create/Setup a MyColors.sublime-color-scheme file which contains a comment and/or trailing commas in objects/lists
2. Open a file within a git repo.
3. Call `git: diff inline`

**Info**

- GitSavvy dev branch at f8b65c8ff3be2aa9dee37e9b10a068be5b8b9968
- Sublime Text 3176 / 3180 x64
- Windows 10 x64

**Console Log**

```
Traceback (most recent call last):
  File "C:\Apps\Sublime Text 3\Data\Packages\GitSavvy\core\commands\inline_diff.py", line 38, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async(**kwargs), 0)
  File "C:\Apps\Sublime Text 3\Data\Packages\GitSavvy\core\commands\inline_diff.py", line 63, in run_async
    self.augment_color_scheme(diff_view, file_ext)
  File "C:\Apps\Sublime Text 3\Data\Packages\GitSavvy\core\commands\inline_diff.py", line 100, in augment_color_scheme
    themeGenerator = JSONThemeGenerator(original_color_scheme)
  File "C:\Apps\Sublime Text 3\Data\Packages\GitSavvy\common\theme_generator.py", line 133, in __init__
    self.dict = json.loads(self.color_scheme_string, object_pairs_hook=OrderedDict)
  File "./python3.3/json/__init__.py", line 329, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 367, in raw_decode
ValueError: Expecting property name enclosed in double quotes: line 38 column 5 (char 1091)
```

**Comment by randy3k** [comment]
Yes, you are right. Mind submitting a PR? I get no time these few weeks to do anything...
