### ISSUE TITLE
[WinError 267] The directory name is invalid

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#105]
Whenever I open up or select a tab with content that should exist on the harddrive but doesn't (file opened from a Zip file so it's in /Temp, or simply opening the Default settings/keybindings for sublime), I will get the error `[WinError 267] The directory name is invalid`, marking the file as dirty.

Also, if I have any of those files opened in Sublime, close Sublime and reopen it, the tab is gone.

I will try and see if I can fix it myself.

**Comment by p3lim** [comment]
Full error:
```
Unable to open /C/Users/Administrator/AppData/Roaming/Sublime Text 3/Packages/Default/Preferences.sublime-settings
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
NotADirectoryError: [WinError 267] The directory name is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 98, in git
    startupinfo=startupinfo)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
NotADirectoryError: [WinError 267] The directory name is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\status_bar.py", line 34, in run_async
    if not self.file_path or not self._repo_path(throw_on_stderr=False):
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 171, in _repo_path
    throw_on_stderr=throw_on_stderr
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 103, in git
    raise_error(e)
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 84, in raise_error
    raise GitSavvyError(msg)
GitSavvy.core.git_command.GitSavvyError: [WinError 267] The directory name is invalid
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
NotADirectoryError: [WinError 267] The directory name is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 98, in git
    startupinfo=startupinfo)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
NotADirectoryError: [WinError 267] The directory name is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\status_bar.py", line 34, in run_async
    if not self.file_path or not self._repo_path(throw_on_stderr=False):
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 171, in _repo_path
    throw_on_stderr=throw_on_stderr
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 103, in git
    raise_error(e)
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 84, in raise_error
    raise GitSavvyError(msg)
GitSavvy.core.git_command.GitSavvyError: [WinError 267] The directory name is invalid
```

**Comment by divmain** [comment]
@p3lim would you mind letting me know if this resolves the issue for you?

**Comment by p3lim** [comment]
That fixed it, thanks

**Comment by divmain** [comment]
Sorry, I just re-read this and realized that you were going to address.

**Comment by nastorga87** [comment]
hi, I hhave the same problem but opening a .npy file.
I try to open a .npy file and I have the next error:

NotADirectoryError: [WinError 267] The directory name is not valid: 'labels.npy'

I define the class said before and put :a=NotADirectoryError(np.load('labels.npy'))

but didn't work

**Comment by asfaltboy** [comment]
Thanks for reporting @nastorga87 , we'll try to deal with regression in the PR #719
