### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'settings'

### ISSUE THREAD

**Issue by rwols** [divmain/GitSavvy#1057]
Hi there. When I open ST with two projects, and then close one quickly, this panel pops up:

```
Please report this error to GitSavvy:

'NoneType' object has no attribute 'settings'

Traceback (most recent call last):
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 215, in git
    stdout, stderr = self.decode_stdout(stdout), self.decode_stdout(stderr)
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 265, in decode_stdout
    fallback_encoding = self.savvy_settings.get("fallback_encoding")
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/settings.py", line 12, in get
    project_savvy_settings = view.settings().get("GitSavvy", {})
AttributeError: 'NoneType' object has no attribute 'settings'
```

- Sublime Text 3180
- git version 2.17.2 (Apple Git-113)
- macOS 10.14

**Comment by randy3k** [comment]
It has been fixed in the dev branch. (forget which PR though)

**Comment by rwols** [comment]
Cool, I'll wait for the release then :)
