### ISSUE TITLE
Error: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#129]
This error is shown in a panel every time a file without a source (e.g. opened from a zip) is opened or in the focused view.

The console shows a flood of the following error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 96, in git
    cwd=working_dir or self.repo_path,
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 148, in repo_path
    return self._repo_path()
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 173, in _repo_path
    throw_on_stderr=throw_on_stderr
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 103, in git
    raise_error(e)
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 84, in raise_error
    raise GitSavvyError(msg)
GitSavvy.core.git_command.GitSavvyError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\status_bar.py", line 34, in run_async
    if not self.file_path or not self._repo_path(throw_on_stderr=False):
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 173, in _repo_path
    throw_on_stderr=throw_on_stderr
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 103, in git
    raise_error(e)
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 84, in raise_error
    raise GitSavvyError(msg)
GitSavvy.core.git_command.GitSavvyError: maximum recursion depth exceeded in comparison
```

**Comment by yyyc514** [comment]
I could look at this is anyone knew how to easily reproduce on Mac platform.

**Comment by p3lim** [comment]
I encountered this on Windows, no idea if it's reproduceable on other systems.

**Comment by yyyc514** [comment]
Yeah, no idea.  I just opened up a single file outside of git and I saw no issues here.

**Comment by divmain** [comment]
@p3lim - this should be fixed in master.  Please let me know if this is still an issue for you.

**Comment by p3lim** [comment]
Yup, that solved it.
