### ISSUE TITLE
'NoneType' object has no attribute 'rfind' when using "Goto Anything"

### ISSUE THREAD

**Issue by alextegelid** [divmain/GitSavvy#132]
I encountered this when quickly switching between files using Goto Anything (CMD+P)

Output from console:

```
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 96, in git
    cwd=working_dir or self.repo_path,
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 148, in repo_path
    return self._repo_path()
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 163, in _repo_path
    file_dir = os.path.dirname(file_path)
  File "./posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/status_bar.py", line 38, in run_async
    short_status = self.get_branch_status_short()
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_mixins/active_branch.py", line 92, in get_branch_status_short
    self._get_branch_status_components()
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_mixins/active_branch.py", line 30, in _get_branch_status_components
    stdout = self.git("status", "-b", "--porcelain").strip()
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 103, in git
    raise_error(e)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 84, in raise_error
    raise GitSavvyError(msg)
GitSavvy.core.git_command.GitSavvyError: 'NoneType' object has no attribute 'rfind'
```

**Comment by divmain** [comment]
@alextegelid, are you on master or 1.3.3?  This looks familiar, and I think it was fixed as part of 36119c98c98127b7c55abc43e1403248385be015.

**Comment by alextegelid** [comment]
Yeah you're probably right. I submitted two issues not long after each other, not realizing they were connected... I see that I added this issue just a couple of hours before you patched it.

**Comment by divmain** [comment]
:+1:  I'll close for now, but if you notice it again, please re-open and ping me.
