### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by pdanpdan** [divmain/GitSavvy#136]
When using git commands (eg. git pull / git status) from an open project, but without an open file, i get the following error:

```python
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 535, in run_
    return self.run()
  File "C:\Program Files\Sublime Text 3\Data\Packages\GitSavvy\core\interfaces\status.py", line 97, in run
    repo_path = self.repo_path
  File "C:\Program Files\Sublime Text 3\Data\Packages\GitSavvy\core\git_command.py", line 148, in repo_path
    return self._repo_path()
  File "C:\Program Files\Sublime Text 3\Data\Packages\GitSavvy\core\git_command.py", line 163, in _repo_path
    view = self.window.active_view() if hasattr(self, "window") else self.view
  File "./ntpath.py", line 316, in dirname
  File "./ntpath.py", line 280, in split
  File "./ntpath.py", line 208, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

I think it should either use the project folder as base directory for git, or show a human readable error.

**Comment by divmain** [comment]
@pdanpdan, are you on master or `1.3.3`?  This looks familiar and may have been fixed by 36119c98c98127b7c55abc43e1403248385be015, which includes a fix for this case and human-readable errors for others.

**Comment by pdanpdan** [comment]
I'm on master

**Comment by divmain** [comment]
Hmm.  Just to be sure, can you pull latest master and restart Sublime?  This looks eerily familiar, so I don't want to dig too deep if it is already resolved.

**Comment by pdanpdan** [comment]
Sorry to have bothered you, i think it wasn't the master, but 1.3.3, because after update the problem is gone, and it gets the project folder all right. Thank you.

**Comment by divmain** [comment]
No worries!  Thanks for letting me know.
