### ISSUE TITLE
Inline diff view won't work after upgrade to 1.4.0

### ISSUE THREAD

**Issue by alextegelid** [divmain/GitSavvy#155]
Since upgrading to the 1.4.0 release the inline diff view shows an empty tab.

**Comment by divmain** [comment]
Hi @alextegelid. It is working on my machine - could you check the console and see if any errors are present?

I'm also considering creating a beta GitSavvy track for users willing to try features before they're released to the wild. That may help to mitigate regressions like this in the future...

**Comment by alextegelid** [comment]
Yes of course!
Sorry, I could've thought of attaching that in the first place.

This is written to console when I open the inline diff view:

```
Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/inline_diff.py", line 36, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async(**kwargs), 0)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/inline_diff.py", line 56, in run_async
    self.augment_color_scheme(diff_view, file_ext)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/inline_diff.py", line 91, in augment_color_scheme
    background=colors["inline_diff"]["add_background_bold"],
KeyError: 'add_background_bold'
```

When switching tabs out of the diff view and back again, this appears (once everytime i re-enter the tab):
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/inline_diff.py", line 139, in run
    working_tree_file_contents = self.get_file_contents(file_path)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/inline_diff.py", line 208, in get_file_contents
    file_path = os.path.join(self.repo_path, file_path)
  File "./posixpath.py", line 80, in join
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by divmain** [comment]
Ah!  Just a guess, did you set alternate colors for the inline-diff view?  If so, you'll need to add additional definitions.  See [here](https://github.com/divmain/GitSavvy/blob/master/GitSavvy.sublime-settings#L39-L46).  I should have put a warning about that in the upgrade message.  Basically, since you're defining all colors for `inline_diff` in your custom view, it won't fall back to the default colors.

**Comment by alextegelid** [comment]
Yup, that's it! Thanks!

**Comment by divmain** [comment]
Excellent!
