### ISSUE TITLE
Issues with "git: status" when working with multiple git repositories

### ISSUE THREAD

**Issue by cgrail** [divmain/GitSavvy#164]
Hi,

I've setup a project which includes multiple git repositories. It works as expected for log etc., so depending on which file is currently opened I can see the log either from one repository or the other. But "git: status" works just fine for one project. When I open git status for the other project I get a blank status view and the following error:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 535, in run_
    return self.run()
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\interfaces\status.py", line 24, in run
    StatusInterface(repo_path=self.repo_path)
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\common\ui.py", line 63, in __init__
    self.view = self.create_view(repo_path)
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\common\ui.py", line 81, in create_view
    self.render()
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\common\ui.py", line 90, in render
    rendered = self._render_template()
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\common\ui.py", line 106, in _render_template
    keyed_content = self.get_keyed_content()
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\common\ui.py", line 144, in get_keyed_content
    for key, render_fn in self.partials.items()
  File "./collections/__init__.py", line 56, in __init__
  File "./collections/abc.py", line 578, in update
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\common\ui.py", line 144, in <genexpr>
    for key, render_fn in self.partials.items()
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\interfaces\status.py", line 194, in render_stashes
    stash_list = self.get_stashes()
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_mixins\stash.py", line 16, in get_stashes
    for entry in stdout.split("\n") if entry
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_mixins\stash.py", line 16, in <listcomp>
    for entry in stdout.split("\n") if entry
AttributeError: 'NoneType' object has no attribute 'groups'
```

Best regards,
Christian

**Comment by divmain** [comment]
Hi @cgrail.  For the project that isn't working, can you go to the terminal and type `git stash list` and tell what shows up there?  This error indicates that the regular expression cannot parse the output of `git stash`, and it is possible I've missed an edge case.

**Comment by cgrail** [comment]
Hi @divmain ,

I get the following response for the command "git stash list":
git stash list                                                   
stash@{0}: WIP on master: 30c7f2d header on repeating blocks & css 
stash@{1}: project                                                 

Best regards,
Christian

**Comment by divmain** [comment]
Interesting!  Looks like the second stash must have been created on detached HEAD.  I'll add a fix for this - thanks!

**Comment by cgrail** [comment]
![git status](https://cloud.githubusercontent.com/assets/5702278/6989727/82a712d0-da14-11e4-9a0d-cebdf15730ae.PNG)

Ok. But my repo is not detached. It's in sync with the remote repo. But I'll try your fix.

**Comment by divmain** [comment]
Sorry if I wasn't clear.  HEAD must've been detached when the stash was created, because the second stash is missing "WIP on <branch name>".  I hadn't considered this case when writing the parser for `git stash`, but I'll have a fix in master in a couple of minutes.

**Comment by divmain** [comment]
Alright, a fix for this will be included in the next release.

**Comment by cgrail** [comment]
cool. 

Thanks for the quick fix. I've temporary deleted my old stashes. Works fine now.
