### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by ihorvorotnov** [divmain/GitSavvy#238]
Hi. Everything was working properly until recent update. Now, when starting Sublime Text 3 (Build 3083) I get this error (see title). I'm on Windows 10. GitSavvy is 2.4.0. Git is available (Git-1.9.5-preview20150319) it PATH.

Here's the full console output on a fresh run:

```
DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Ihor/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Ihor/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Ihor/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.085149
startup time: 0.141149
first paint time: 0.142149
reloading plugin Default.block

... // I've skipped many plugins here to make it shorter

reloading plugin SublimeCodeIntel.SublimeCodeIntel
plugins loaded
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 106, in git
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.commands.status_bar in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 216, in _repo_path
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 111, in git
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 92, in raise_error
GitSavvy.core.git_command.GitSavvyError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 106, in git
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.commands.status_bar in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 216, in _repo_path
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 111, in git
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 92, in raise_error
GitSavvy.core.git_command.GitSavvyError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 106, in git
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.commands.status_bar in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 216, in _repo_path
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 111, in git
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 92, in raise_error
GitSavvy.core.git_command.GitSavvyError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 106, in git
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.commands.status_bar in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 216, in _repo_path
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 111, in git
  File "core.git_command in C:\Users\Ihor\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 92, in raise_error
GitSavvy.core.git_command.GitSavvyError: [WinError 2] The system cannot find the file specified
Package Control: Skipping automatic upgrade, last run at 2015-09-17 17:54:02, next run at 2015-09-17 18:54:02 or after
```

Any ideas how to fix this?

**Comment by divmain** [comment]
Most likely GitSavvy is unable to determine your Git path.  If this happened with the most recent upgrade, I suspect it has to do with [this commit](https://github.com/divmain/GitSavvy/commit/5640e2bb603ebe70c3a2a45059abc12095efdc5b).  Can you tell me what that part of your config looks like?  And perhaps attempt to set the `git_path` value in the various ways shown?  Let me know what comes of that attempt...

**Comment by ihorvorotnov** [comment]
In settings I have:
```
"git_path": {
    "default": "",
    "windows": "C:/Program Files/Git/cmd/git.exe"
},
```

and now it makes sense. In 64-bit Windows versions (100% on Windows 7 and Windows 10, I guess it's safe to assume the same for Windows 8, 8.1 as well) Git is installed in `Program Files (x86)` folder.

Copied this part to user settings and modified path, works fine.

The issue is solved in my case, however, x64 is pretty popular and Git for Windows has x86 architecture. I bet it will throw this error  on every standard setup with Win x64, Git and GitSavvy. If it's possible with Python, you should check for OS architecture and use appropriate path. Or, at least adding a note to README / Installation guide would be useful.

Closing this.

**Comment by divmain** [comment]
Thanks, I added a note.

**Comment by bmix** [comment]
Hmmm...I just had the same error message after updating my Git installation on Windows 10. 

> Please report this error to GitSavvy:
>
> [WinError 2] Das System kann die angegebene Datei nicht finden

(Translated error message is same as for user @ihorvorotnov)

Before, I had the 32 bit version of Git installed, it was pretty old, so, today, I downloaded the current 64 bit package and it, correctly, installed to `"C:\Program Files\Git\cmd\git.exe"`. This means, that now Git correctly installs to the folder, that contains the 64 bit applications on a Win64 OS.

My configuration is:
```json
"git_path": {
  "default": "",
  "windows": "C:/Program Files/Git/cmd/git.exe"
}
```
