### ISSUE TITLE
[WinError 5] Access is denied?

### ISSUE THREAD

**Issue by erikblake** [divmain/GitSavvy#283]
I installed gutsavvy on Sublime3 running on Win7-64. Now, whenever I open Sublime, I get a dialog with the message "[WinError 5] Access is denied". I do not have git in the PATH, so I have git_path set in gitcavvy.sublime-settings - user. I've tried both "C:\\PF\\Git\\bin" and "C:\\PF\\Git" for the path value.

Traceback is as follows:

    DPI scale: 1
    startup, version: 3095 windows x64 channel: dev
    executable: /C/Program Files/Sublime Text 3/sublime_text.exe
    working dir: /C/Program Files/Sublime Text 3
    packages path: /C/Users/xxx/AppData/Roaming/Sublime Text 3/Packages
    state path: /C/Users/xxx/AppData/Roaming/Sublime Text 3/Local
    zip path: /C/Program Files/Sublime Text 3/Packages
    zip path: /C/Users/xxx/AppData/Roaming/Sublime Text 3/Installed Packages
    ignored_packages: ["Vintage"]
    pre session restore time: 0.163135
    startup time: 0.206135
    first paint time: 0.207135
    reloading plugin Default.block
    reloading plugin Default.comment
    reloading plugin Default.convert_syntax
    reloading plugin Default.copy_path
    reloading plugin Default.delete_word
    reloading plugin Default.detect_indentation
    reloading plugin Default.duplicate_line
    reloading plugin Default.echo
    reloading plugin Default.exec
    reloading plugin Default.fold
    reloading plugin Default.font
    reloading plugin Default.goto_line
    reloading plugin Default.history_list
    reloading plugin Default.indentation
    reloading plugin Default.kill_ring
    reloading plugin Default.mark
    reloading plugin Default.new_templates
    reloading plugin Default.open_context_url
    reloading plugin Default.open_file_settings
    reloading plugin Default.open_in_browser
    reloading plugin Default.pane
    reloading plugin Default.paragraph
    reloading plugin Default.paste_from_history
    reloading plugin Default.quick_panel
    reloading plugin Default.run_all_syntax_tests
    reloading plugin Default.save_on_focus_lost
    reloading plugin Default.scroll
    reloading plugin Default.set_unsaved_view_name
    reloading plugin Default.side_bar
    reloading plugin Default.sort
    reloading plugin Default.swap_line
    reloading plugin Default.switch_file
    reloading plugin Default.symbol
    reloading plugin Default.transform
    reloading plugin Default.transpose
    reloading plugin Default.trim_trailing_white_space
    reloading plugin CSS.css_completions
    reloading plugin Diff.diff
    reloading plugin HTML.encode_html_entities
    reloading plugin HTML.html_completions
    reloading plugin 0_package_control_loader.00-package_control
    reloading plugin 0_package_control_loader.02-bz2
    reloading plugin GitSavvy.git_savvy
    reloading plugin LaTeX Word Count.WordCount
    reloading plugin Origami.origami
    reloading plugin Package Control.1_reloader
    reloading plugin Package Control.2_bootstrap
    reloading plugin Package Control.Package Control
    reloading plugin WordCount.WordCount
    reloading plugin User.characterCounter
    plugins loaded
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Package Control: Skipping automatic upgrade, last run at 2015-11-03 08:29:02, next run at 2015-11-03 09:29:02 or after
    Unable to open /C/Users/xxx/AppData/Roaming/Sublime Text 3/Packages/GitSavvy/GitSavvy.sublime-settings
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied
    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 119, in git
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    PermissionError: [WinError 5] Access is denied

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "core.commands.status_bar in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 34, in run_async
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 228, in _repo_path
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 124, in git
      File "core.git_command in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package", line 105, in raise_error
    GitSavvy.core.git_command.GitSavvyError: [WinError 5] Access is denied

See attached screen capture.

![image](https://cloud.githubusercontent.com/assets/2335585/10914662/3644f8e8-8208-11e5-99a3-2f44cd92da10.png)

**Comment by divmain** [comment]
Hey @erikblake, you'll want to use the full path to the Git binary itself (not just the directory where it is located).  Based on what you've posted, this value is probably `C:\\PF\\Git\\cmd\\git.exe`.

**Comment by erikblake** [comment]
That did indeed solve the issue! Thanks!

I guess I assumed "git_path" meant the directory/folder, since that's what would be present in the PATH environment variable, had I used this option when installing git. Maybe this could be clarified in the documentation under the "Simple Installation" note.
