### ISSUE TITLE
failed to import `yaml` module

### ISSUE THREAD

**Issue by demon386** [divmain/GitSavvy#383]
```
File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 696, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "common.util.file in /Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 2, in <module>
ImportError: No module named 'yaml'
```

OS: OS X EI Capitan
Sublime: Sublime Text 3 Build 3109 (Dev Build)

**Comment by majkiee** [comment]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 696, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "git_savvy in /Users/micke/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 35, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 696, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "common.commands in /Users/micke/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 1, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 696, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "common.commands.debug in /Users/micke/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 12, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 696, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "common.util in /Users/micke/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 696, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "common.util.file in /Users/micke/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 2, in <module>
ImportError: No module named 'yaml'

```
OS: OS X EI Capitan
Sublime: Sublime Text 3 Build 3103

**Comment by divmain** [comment]
@demon386 @majkiee, I just pushed out an update that will disable the offending code as a temporary work-around.  Syntax highlighting will disabled in inline-diff views, but we'll address that regression separately.  If you see this in the next few minutes, it would be super helpful if you could pull down master and confirm that things are working for you.  Sorry for the bad update!

**Comment by demon386** [comment]
It's fixed now. Thanks for the quick response.
