### ISSUE TITLE
Error in version v2016.06.27.01.18.40; github.com/divmain/GitSavvy

### ISSUE THREAD

**Issue by pdanpdan** [divmain/GitSavvy#443]
- startup, version: 3117 linux x64 channel: dev

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 83, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 702, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "git_savvy in /home/pdan/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 702, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "core.interfaces in /home/pdan/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 702, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "core.interfaces.branch in /home/pdan/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 498
    return self.get_selected_branch_name(sel, line) for line in lines
                                                      ^
SyntaxError: invalid syntax
```

**Comment by stoivo** [comment]
It is fixed now.
