### ISSUE TITLE
Invalid syntax branch.py, line 498

### ISSUE THREAD

**Issue by alextegelid** [divmain/GitSavvy#444]
Since earlier today I'm getting this when launching ST3 (stable, 3114), which prevents GitSavvy from running at all. The funny thing is that I didn't upgrade anything (at least not what I could see) between it working and now. I'm on the master branch here on GitHub, bypassing wbond's Package Control.

```
reloading plugin GitSavvy.git_savvy
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/alextegelid/Library/Application Support/Sublime Text 3/Packages/GitSavvy/git_savvy.py", line 39, in <module>
    from .core.interfaces import *
  File "/Users/alextegelid/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/interfaces/__init__.py", line 5, in <module>
    from .branch import *
  File "/Users/alextegelid/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/interfaces/branch.py", line 498
    return self.get_selected_branch_name(sel, line) for line in lines
                                                      ^
SyntaxError: invalid syntax
```

**Comment by alextegelid** [comment]
Maybe related to https://github.com/divmain/GitSavvy/commit/321112e36164cb82f389e71040a2efa808e033cd? Can you confirm @stoivo?

**Comment by alextegelid** [comment]
I can comfirm that `GitSavvy v2.10.1` currently available from Package Control is working

**Comment by stoivo** [comment]
It is fixed now on master.

Thanks.

**Comment by alextegelid** [comment]
Nice work, thanks!

**Comment by alextegelid** [comment]
Actually, now I'm encountering an error when merging:

```
Traceback (most recent call last):
  File "/Users/alextegelid/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/interfaces/branch.py", line 492, in run_async
    branches = set(branch for branch in branches if branch and not branch == current_branch_name)
TypeError: unhashable type: 'list'
```

**Comment by divmain** [comment]
I'll take a look!

**Comment by alextegelid** [comment]
I should probably learn python. This seems to be rather simple things to fix. Maybe next time I can propose a ready-to-go fix. 

As always, you're doing a really good job, all of you ❤️

**Comment by stoivo** [comment]
I had a look at it, check that is works https://github.com/divmain/GitSavvy/commit/91f6583934e076dc8d76bea3f94f858a86abf084.

**Comment by divmain** [comment]
@alextegelid, let us know if we need to reopen.  Thanks!

**Comment by alextegelid** [comment]
Sorry for the slow response, I've been on vacation.

Merging now works without any trouble. Good job!
