### ISSUE TITLE
git: blame current file results in AttributeError

### ISSUE THREAD

**Issue by iamolivinius** [divmain/GitSavvy#48]
git 1.9.3
sublime 3065
ubuntu linux 14.04

```bash
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "/home/oliver/.config/sublime-text-3/Packages/GitSavvy/core/commands/blame.py", line 39, in run
    content = self.get_content()
  File "/home/oliver/.config/sublime-text-3/Packages/GitSavvy/core/commands/blame.py", line 50, in get_content
    blamed_lines, commits = self.parse_blame(blame_porcelain.splitlines())
  File "/home/oliver/.config/sublime-text-3/Packages/GitSavvy/core/commands/blame.py", line 100, in parse_blame
    k, v = re.match(r"([^ ]+) (.+)", next_line).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by divmain** [comment]
Could you paste the output of `git blame FILENAME` for the file this fails for?

**Comment by iamolivinius** [comment]
`encoding UTF-8` works fine
`encoding UTF-8 with BOM` fails
`encoding UTF-16 LE` fails
`encoding UTF-16 LE with BOM` fails
`encoding UTF-16 BE` fails
`encoding UTF-16 BE with BOM` fails

That's the `git blame` output (first line) of an UTF-8 with BOM encoded file
```
1085bf15 (Felix Epp       2015-03-07 18:06:09 +0100  1) <U+FEFF>import log from 'rose/log';
```

Since git doesn't handle these file encodings either I guess there's not much to fix here. Maybe a readable error message for the user would be nice.

**Comment by divmain** [comment]
@iamolivinius - it may be possible to support this, but it'll require a bit more investigation on my part.  I've just added a feature (will be in the release later this evening) that enables recording of the underlying interactions with Git.  Once GitSavvy is updated on your machine, would you mind doing the following:

1. In the command palette, run `GitSavvy: start logging`.
2. Reproduce the error.
3. In the command palette, run `GitSavvy: stop logging`.
4. In the command palette, run `GitSavvy: view recorded log`.

Copy the output into a comment here, and I should have better luck seeing if I can add support for non-UTF-8.

**Comment by iamolivinius** [comment]
There you go!

```json
[
  {
    "type": "git", 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stdin": null, 
    "stderr": "", 
    "stdout": "/home/oliver/Documents/gulpicRose\n"
  }, 
  {
    "type": "git", 
    "command": [
      "blame", 
      "-p", 
      "/home/oliver/Documents/gulpicRose/app/extension_info.json"
    ], 
    "stdin": null, 
    "stderr": "", 
    "stdout": "0000000000000000000000000000000000000000 1 1 1\nauthor Not Committed Yet\nauthor-mail <not.committed.yet>\nauthor-time 1426005957\nauthor-tz +0100\ncommitter Not Committed Yet\ncommitter-mail <not.committed.yet>\ncommitter-time 1426005957\ncommitter-tz +0100\nsummary Version of app/extension_info.json from app/extension_info.json\nprevious 85c6cb7fa4f66cb10b9bb05c10653314aeb68a1c app/extension_info.json\nfilename app/extension_info.json\n\t\ufeff{\n1f45c813b82e7cf0d54435df9ce41469fb6a67a6 2 2 5\nauthor Felix Epp\nauthor-mail <felix.epp@sit.fraunhofer.de>\nauthor-time 1425390254\nauthor-tz +0100\ncommitter Felix Epp\ncommitter-mail <felix.epp@sit.fraunhofer.de>\ncommitter-time 1425390254\ncommitter-tz +0100\nsummary Extension Meta Data and Icons from v2\nprevious 6d8ac83bb71ea5bdef32454d7727339e883f4699 app/extension_info.json\nfilename app/extension_info.json\n\t    \"name\": \"ROSE\",\n1f45c813b82e7cf0d54435df9ce41469fb6a67a6 3 3\n\t    \"description\": \"Research tool for field studies in online social networks.\",\n1f45c813b82e7cf0d54435df9ce41469fb6a67a6 4 4\n\t    \"creator\": \"Fraunhofer Institute SIT\",\n1f45c813b82e7cf0d54435df9ce41469fb6a67a6 5 5\n\t    \"version\": \"3.0.0\",\n1f45c813b82e7cf0d54435df9ce41469fb6a67a6 6 6\n\t    \"homepage_url\": \"https://dipo.sit.fraunhofer.de/\",\nc549f06a727f47f65e72bc147db2babcfa7e1fd5 5 7 1\nauthor Oliver Hoffmann\nauthor-mail <oliverh855@gmail.com>\nauthor-time 1423767576\nauthor-tz +0100\ncommitter Oliver Hoffmann\ncommitter-mail <oliverh855@gmail.com>\ncommitter-time 1423767576\ncommitter-tz +0100\nsummary Initial commit\nboundary\nfilename app/extension_info.json\n\t    \"background_scripts\": [\na8a83984b60a658449361e0290b7e68442644fc6 6 8 1\nauthor Oliver Hoffmann\nauthor-mail <oliverh855@gmail.com>\nauthor-time 1423844615\nauthor-tz +0100\ncommitter Oliver Hoffmann\ncommitter-mail <oliverh855@gmail.com>\ncommitter-time 1423844615\ncommitter-tz +0100\nsummary work on buil system and autoreload\nprevious ab02d40cd19a4d1cdf11feb234083b6ce6e4bea9 app/extension_info.json\nfilename app/extension_info.json\n\t        \"scripts/chromereload.js\",\nb4dbb85f4756a9c337bdfcdb2bf3c2d6daf1dd58 6 9 1\nauthor Oliver Hoffmann\nauthor-mail <oliverh855@gmail.com>\nauthor-time 1424345172\nauthor-tz +0100\ncommitter Oliver Hoffmann\ncommitter-mail <oliverh855@gmail.com>\ncommitter-time 1424345172\ncommitter-tz +0100\nsummary Fixes import and require bug\nprevious 3e424624f0c81bba220c2c2b7c6b26ae349e9e02 app/extension_info.json\nfilename app/extension_info.json\n\t        \"bower_components/jquery/dist/jquery.js\",\n0000000000000000000000000000000000000000 10 10 1\n\t         \"bower_components/underscore/underscore.js\",\nd3b3cd0f58c4939261d2d4237a9ab41664021508 11 11 1\nauthor Oliver Hoffmann\nauthor-mail <oliverh855@gmail.com>\nauthor-time 1425392434\nauthor-tz +0100\ncommitter Oliver Hoffmann\ncommitter-mail <oliverh855@gmail.com>\ncommitter-time 1425392911\ncommitter-tz +0100\nsummary Added backbone and kango-localforage-backbone adapter\nprevious 1f45c813b82e7cf0d54435df9ce41469fb6a67a6 app/extension_info.json\nfilename app/extension_info.json\n\t        \"bower_components/backbone/backbone.js\",\n05463136bc5cb2b9a2ce8761e0bb8f09532f6ae4 6 12 1\nauthor Oliver Hoffmann\nauthor-mail <oliverh855@gmail.com>\nauthor-time 1423787905\nauthor-tz +0100\ncommitter Oliver Hoffmann\ncommitter-mail <oliverh855@gmail.com>\ncommitter-time 1423787905\ncommitter-tz +0100\nsummary more work on build process\nprevious c549f06a727f47f65e72bc147db2babcfa7e1fd5 app/extension_info.json\nfilename app/extension_info.json\n\t        \"bower_components/localforage/dist/localforage.js\",\nd3b3cd0f58c4939261d2d4237a9ab41664021508 13 13 2\n\t        \"bower_components/kango-localforage-backbone/dist/localforage.backbone.js\",\nd3b3cd0f58c4939261d2d4237a9ab41664021508 14 14\n\t        \"bower_components/fetch/fetch.js\",\nc549f06a727f47f65e72bc147db2babcfa7e1fd5 6 15 4\n\t        \"background_app.js\"\nc549f06a727f47f65e72bc147db2babcfa7e1fd5 7 16\n\t    ],\nc549f06a727f47f65e72bc147db2babcfa7e1fd5 8 17\n\t    \"content_scripts\": [\nc549f06a727f47f65e72bc147db2babcfa7e1fd5 9 18\n\t        \"bower_components/jquery/dist/jquery.js\",\n6d8ac83bb71ea5bdef32454d7727339e883f4699 12 19 1\nauthor Felix Epp\nauthor-mail <felix.epp@sit.fraunhofer.de>\nauthor-time 1425386189\nauthor-tz +0100\ncommitter Felix Epp\ncommitter-mail <felix.epp@sit.fraunhofer.de>\ncommitter-time 1425386189\ncommitter-tz +0100\nsummary Crypto Moduel: use forge bundle for hashing\nprevious 9901adbbd63ab4083eb122e8ef57eeb7f5ef6cec app/extension_info.json\nfilename app/extension_info.json\n\t        \"bower_components/forge/js/forge.min.js\",\nd3b3cd0f58c4939261d2d4237a9ab41664021508 20 20 4\n\t        \"bower_components/underscore/underscore.js\",\nd3b3cd0f58c4939261d2d4237a9ab41664021508 21 21\n\t        \"bower_components/backbone/backbone.js\",\nd3b3cd0f58c4939261d2d4237a9ab41664021508 22 22\n\t        \"bower_components/localforage/dist/localforage.js\",\nd3b3cd0f58c4939261d2d4237a9ab41664021508 23 23\n\t        \"bower_components/kango-localforage-backbone/dist/localforage.backbone.js\",\nb6eb44ca89f47d7546b336f92e1f3e320380b00d 24 24 1\nauthor Felix Epp\nauthor-mail <work@felixepp.de>\nauthor-time 1425585880\nauthor-tz +0100\ncommitter Felix Epp\ncommitter-mail <work@felixepp.de>\ncommitter-time 1425585880\ncommitter-tz +0100\nsummary FacebookUI: add costum semantic-ui package and build deps and specs\nprevious fd3b453d329f0edd89654c30601976588dfdd3f6 app/extension_info.json\nfilename app/extension_info.json\n\t        \"res/semantic/semantic.min.js\",\nfd3b453d329f0edd89654c30601976588dfdd3f6 25 25 5\nauthor Felix Epp\nauthor-mail <felix.epp@sit.fraunhofer.de>\nauthor-time 1425410654\nauthor-tz +0100\ncommitter Felix Epp\ncommitter-mail <felix.epp@sit.fraunhofer.de>\ncommitter-time 1425410654\ncommitter-tz +0100\nsummary FacebookUI: Include module in contentscript, inject html unfixed: semantic-ui.css, storage; ObserverEngine: check networks in content script; Package info completed\nprevious bd613d17e5467c306d6907c5faa5251a11f79c59 app/extension_info.json\nfilename app/extension_info.json\n\t        \"bower_components/rsvp/rsvp.min.js\",\nfd3b453d329f0edd89654c30601976588dfdd3f6 26 26\n\t        \"bower_components/handlebars/handlebars.min.js\",\nfd3b453d329f0edd89654c30601976588dfdd3f6 27 27\n\t        \"bower_components/i18next/i18next.min.js\",\nfd3b453d329f0edd89654c30601976588dfdd3f6 28 28\n\t        \"res/locales/de/translation.json\",\nfd3b453d329f0edd89654c30601976588dfdd3f6 29 29\n\t        \"res/locales/en/translation.json\",\n0e1fb730b05db32d647712d36b73d24cebf0cc86 12 30 1\nauthor Felix Epp\nauthor-mail <felix.epp@sit.fraunhofer.de>\nauthor-time 1425382481\nauthor-tz +0100\ncommitter Felix Epp\ncommitter-mail <felix.epp@sit.fraunhofer.de>\ncommitter-time 1425382481\ncommitter-tz +0100\nsummary Fix built script: removed obsolete file ref from manifest\nprevious a2ffa678b306ef82a4e974ab5729c9a47f96bfc2 app/extension_info.json\nfilename app/extension_info.json\n\t        \"content_app1.js\"\nc549f06a727f47f65e72bc147db2babcfa7e1fd5 12 31 1\n\t    ],\nc549f06a727f47f65e72bc147db2babcfa7e1fd5 15 32 1\n\t    \"browser_button\": {\n1f45c813b82e7cf0d54435df9ce41469fb6a67a6 19 33 4\n\t        \"caption\": \"ROSE\",\n1f45c813b82e7cf0d54435df9ce41469fb6a67a6 20 34\n\t        \"tooltipText\": \"ROSE Browser Plugin\",\n1f45c813b82e7cf0d54435df9ce41469fb6a67a6 21 35\n\t        \"icon\": \"icons/button.png\"\n1f45c813b82e7cf0d54435df9ce41469fb6a67a6 22 36\n\t    }\nc549f06a727f47f65e72bc147db2babcfa7e1fd5 21 37 1\n\t}\n"
  }
]
```

**Comment by divmain** [comment]
Thanks for the log output @iamolivinius.  Just cc'd you on a commit, which is now in master.  Can you confirm that the change fixes the issue you were seeing?  From appearances, this had nothing to do with the encoding of the file.

**Comment by iamolivinius** [comment]
Thanks, this fixes the blame command for me! :+1:
