### ISSUE TITLE
Git clone fails when not currently in a repo

### ISSUE THREAD

**Issue by asfaltboy** [divmain/GitSavvy#613]
I may be hitting a user error, but simply trying to clone a repo such as `git@github.com:Hammerspoon/hammerspoon.git` failed with: "Unable to determine Git repo path." (traceback below)

I answered first prompt with the repo URI, and the second prompt with a local path. It seems I MUST be on some kind of git repo, either bare or other. We can probably avoid this requirement for the git clone command at least.

```python
Traceback (most recent call last):
  File "/Users/pavel/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 126, in git
    cwd=working_dir or self.repo_path,
  File "/Users/pavel/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 213, in repo_path
    return self._repo_path()
  File "/Users/pavel/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 246, in _repo_path
    return invalid_repo()
  File "/Users/pavel/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 230, in invalid_repo
    raise ValueError("Unable to determine Git repo path.")
ValueError: Unable to determine Git repo path.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pavel/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/init.py", line 131, in do_clone
    self.git("clone", self.git_url, self.suggested_git_root)
  File "/Users/pavel/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 134, in git
    raise_error(e)
  File "/Users/pavel/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 112, in raise_error
    raise GitSavvyError(msg)
GitSavvy.core.exceptions.GitSavvyError: Unable to determine Git repo path.

```

**Comment by stoivo** [comment]
Hmm, that is stage I did just cloned it and it works. See here http://recordit.co/i8j8wIXrZ7

I changes it to be async recently so if it take longer to clone a repo you don't much of a feedback before it is done.

**Comment by asfaltboy** [comment]
It only fails when you run the command outside of a repo, e.g open a new window first.

![efu4djdwmv](https://cloud.githubusercontent.com/assets/321520/23581631/b5caa1f0-0117-11e7-9612-72118e53d627.gif)

**Comment by stoivo** [comment]
It enter an infinite loop trying to find the working tree. So by simply passing a valid path to the git command with it should prevent it. PR at #616
