### ISSUE TITLE
Rebase: commit manipulation no longer works in certain situations

### ISSUE THREAD

**Issue by allen-zeng** [divmain/GitSavvy#641]
Recently the rebase view doesn't work on one of my repos any more. The error messages printed in the console:
> Traceback (most recent call last):
  File "core.interfaces.rebase in /Users/Allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 679, in run_async
  File "core.interfaces.rebase in /Users/Allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 504, in get_idx_entry_and_prev
UnboundLocalError: local variable 'selected_idx' referenced before assignment

The logs (with some information redacted):
```
[
  {
    "command": [
      "branch", 
      "--no-color"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "  branch1\n  branch2\n  branch3\n  branch4\n* branch5\n  branch6\n"
  }, 
  {
    "command": [
      "merge-base", 
      "HEAD", 
      "origin/branch2"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n"
  }, 
  {
    "command": [
      "log", 
      "-6000", 
      null, 
      "--reverse", 
      "--format=%h%n%H%n%s%n%an%n%ae%n%at%x00%B%x00%x00%n", 
      null, 
      null, 
      null, 
      null, 
      null, 
      null, 
      "--no-merges", 
      null, 
      "--topo-order", 
      null, 
      "<Redacted SHA>..HEAD", 
      null, 
      null, 
      null
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n<Redacted SHA>\n<Redacted commit message>\nAllen Zeng\n<Redacted email>\n1493360704\u0000<Redacted commit message>\n\u0000\u0000\n\n<Redacted SHA>\n<Redacted SHA>\n<Redacted commit message>\nAllen Zeng\n<Redacted email>\n1493378358\u0000<Redacted message>\n\u0000\u0000\n\n<Redacted SHA>\n<Redacted SHA>\n<Redacted message>\nAllen Zeng\n<Redacted email>\n1493378381\u0000<Redacted message>\n\u0000\u0000\n\n<Redacted SHA>\n<Redacted SHA>\n<Redacted message>\nAllen Zeng\n<Redacted email>\n1493378394\u0000<Redacted message>\n\u0000\u0000\n\n"
  }, 
  {
    "command": [
      "merge-base", 
      "HEAD", 
      "origin/branch2"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n"
  }, 
  {
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "## branch5\n"
  }, 
  {
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "## branch5\n"
  }, 
  {
    "command": [
      "merge-base", 
      "HEAD", 
      "origin/branch2"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n"
  }, 
  {
    "command": [
      "merge-base", 
      "<Redacted SHA>", 
      "HEAD"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n"
  }, 
  {
    "command": [
      "rev-parse", 
      "origin/branch2"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n"
  }, 
  {
    "command": [
      "merge-base", 
      "HEAD", 
      "origin/branch2"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n"
  }, 
  {
    "command": [
      "rev-list", 
      "--count", 
      "<Redacted SHA>..HEAD"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "4\n"
  }, 
  {
    "command": [
      "branch", 
      "--no-color"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "  branch1\n  branch2\n  branch3\n  branch4\n* branch5\n  branch6\n"
  }, 
  {
    "command": [
      "show-ref", 
      "refs/heads/branch5"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA> refs/heads/branch5\n"
  }, 
  {
    "command": [
      "status", 
      "--porcelain", 
      "-z"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": ""
  }, 
  {
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted path>\n"
  }, 
  {
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "## branch5\n"
  }, 
  {
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "## branch5\n"
  }
]
```

Again, this doesn't happen in all repos.

Any help is appreciated!

**Comment by randy3k** [comment]
For some reasons, the entry that you selected has a SHA which is different from those of the entry list. It is odd...

**Comment by allen-zeng** [comment]
Not sure what you mean? Have I left out some important information in the logs?

**Comment by allen-zeng** [comment]
I should mention, I was trying to perform any one of the operations in the "Manipulate Commits" section: move up/down, squash etc.

**Comment by randy3k** [comment]
If you don't mind, would you share the uncensored version of
```
"stdout": "<Redacted SHA>\n<Redacted SHA>\n<Redacted commit message>\nAllen Zeng\......"
```

If you cannot provide such, would you kindly confirm that it is in the form of
```
f495173
f495173e92e9cc67147dc9c828939b2b3478a0e4
Fix: Drop a stash is destructive
Simon
simon.toivo@telhaug.no
1488656802\u0000Fix: Drop a stash is destructive

fix #609
\u0000\u0000

eb70249
eb70249e724f933255b4d8c7096092f2764942b4
Fix: support parsing \"git://\" remote URI to Github URL
Pavel Savchenko
asfaltboy@gmail.com
1488650193\u0000Fix: support parsing \"git://\" remote URI to Github URL

This commit also logs an error in case parsing fails.

Fix #612
\u0000\u0000

b1ef1e7
b1ef1e7f78b05db0027cb0c9bb50de368cc1eac7
Release 2.14.1
Simon
simon.toivo@telhaug.no
1489144280\u0000Release 2.14.1
\u0000\u0000
```

**Comment by randy3k** [comment]
My hypothesis is that GitSavvy was making a bad assumption that the shortened version SHAs are always of length 7.

**Comment by allen-zeng** [comment]
I think you're right on the money there @randy3k - all my shortened SHAs have 9 characters.

**Comment by asfaltboy** [comment]
I bet this would affect other code sections as well.

We could make a smarter decision on hash length, with any of the above:
1. Query the git config `core.abbrev` (once per repo), and use it if set, otherwise default to 7.
2. Derive "max length" from any single commit returned
3. Explicitly ask for given length with `--abbrev`, or shortest possible with `--short`, which would then force us to use option 2 above to derive the actual length.

**Comment by randy3k** [comment]
I would go for option 2.

**Comment by randy3k** [comment]
Opps, sorry for the repeated fixups...
