### ISSUE TITLE
Inline diff shows empty tab

### ISSUE THREAD

**Issue by grimborg** [divmain/GitSavvy#66]
Inline diff (cached or not) just shows an empty tab. Regular diff works, though. Using ST3 build 3075.

**Comment by divmain** [comment]
Hey @grimborg, is it always broken for you or only under certain conditions?  If you don't mind, can you do the following?

1. Open the command palette and type `GitSavvy: start logging`.
2. Try to open an inline-diff view for a file that wasn't working before.
3. Open the command palette and type `GitSavvy: stop logging`.
4. Open the command palette and type `GitSavvy: view recorded log`.

Also, if you open the console and notice any exceptions related to GitSavvy, that would also be helpful.

**Comment by divmain** [comment]
Wondering if this is for files that were previously untracked.  I never got that to work properly (because the compare-to version isn't tracked by Git).  Whether it is or not, the behavior for inline-diffing previously untracked files should be more explicit.

**Comment by dsusini** [comment]
I'm having the same issue while testing on a single file with a single edit.  I followed your directions from above.  Looks like I'm getting a python crash in the console:

Traceback (most recent call last):
  File "C:\Users\--------\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\inline_diff.py", line 36, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async(**kwargs), 0)
  File "C:\Users\--------\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\inline_diff.py", line 56, in run_async
    self.augment_color_scheme(diff_view, file_ext)
  File "C:\Users\--------\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\inline_diff.py", line 75, in augment_color_scheme
    themeGenerator = ThemeGenerator(original_color_scheme)
  File "C:\Users\--------\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\common\theme_generator.py", line 46, in __init__
    self.plist = ElementTree.XML(color_scheme_xml)
  File "./xml/etree/ElementTree.py", line 1356, in XML
xml.etree.ElementTree.ParseError: syntax error: line 2, column 48

Here is the log with private info replaced with "--------":
[
  {
    "stderr": "", 
    "stdin": null, 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stdout": "## master\n M src/--------.cpp\n", 
    "type": "git"
  }, 
  {
    "stderr": "", 
    "stdin": null, 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stdout": "## master\n M src/--------.cpp\n", 
    "type": "git"
  }, 
  {
    "stderr": "", 
    "stdin": null, 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stdout": "W:/Projects/--------\n", 
    "type": "git"
  }, 
  {
    "stderr": "", 
    "stdin": null, 
    "command": [
      "ls-files", 
      "-s", 
      null
    ], 
    "stdout": "100644 bb502cbea566739c4736bd63cd9860806e612eeb 0\t.gitignore\n100644 839594f987664c7538ef0f21862b772c180402d1 0\--------.sln\n100644 

LISTS ALL FILES IN PROJECT HERE..........

I think the below is my gitignore file contents:
    "type": "git"
  }, 
  {
    "stderr": "", 
    "stdin": null, 
    "command": [
      "show", 
      "bb502cbea566739c4736bd63cd9860806e612eeb"
    ], 
    "stdout": "build/\n*.suo\n*.sublime-workspace\n", 
    "type": "git"
  }
]


Also, when I "Stop Logging" and "View log contents" I get a different python crash in the console:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "C:\Users\dsusini\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\inline_diff.py", line 127, in run
    working_tree_file_contents = self.get_file_contents(file_path)
  File "C:\Users\dsusini\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\inline_diff.py", line 193, in get_file_contents
    file_path = os.path.join(self.repo_path, file_path)
  File "./ntpath.py", line 121, in join
  File "./ntpath.py", line 102, in isabs
  File "./ntpath.py", line 208, in splitdrive
TypeError: object of type 'NoneType' has no len()

Hope this helps :)

**Comment by jlangston** [comment]
Having the same issue this is the exception I get in the console. 


>File "/Users/user/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/inline_diff.py", line 36, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async(**kwargs), 0)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/inline_diff.py", line 56, in run_async
    self.augment_color_scheme(diff_view, file_ext)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/inline_diff.py", line 91, in augment_color_scheme
    background=colors["inline_diff"]["add_background_bold"],
KeyError: 'add_background_bold' 
>

**Comment by alextegelid** [comment]
That's actually another issue @jlangston, I had the same one, see #155 
:)

**Comment by jlangston** [comment]
@alextegelid Thanks for pointing that out!

**Comment by divmain** [comment]
Thanks @alextegelid :)

**Comment by divmain** [comment]
@grimborg, I'm going to close this out.  If you or anyone else runs into something similar, let me know and I'll reopen.

**Comment by thezimmee** [comment]
Hi @divmain. I recently starting running into this issue as well, where inline diff pulls up a blank tab. This has worked just fine forever, but now this error occurs for any file / inline diffs I try to run. I'm using ST3 build 3142. Here is the error I get in the console:

```
Traceback (most recent call last):
  File "core.commands.inline_diff in /Volumes/Home/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 37, in <lambda>
  File "core.commands.inline_diff in /Volumes/Home/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 62, in run_async
  File "core.commands.inline_diff in /Volumes/Home/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 96, in augment_color_scheme
  File "common.theme_generator in /Volumes/Home/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 46, in __init__
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XML
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 7, column 3
```

Thanks for any help.

**Comment by stoivo** [comment]
Hi,

It looks like your color scheme is not well-formed xml on line 7. To find the active color_scheme open the console and run `view.settings().get("color_scheme")`. If you can't find the issue in the xml, post the path and the file here.

**Comment by thezimmee** [comment]
@stoivo Thank you, that was it. I removed the characters it didn't like in the color scheme and it works. Thanks again!

**Comment by stoivo** [comment]
Cool, was is a custom created scheme or a packaged one?
