### ISSUE TITLE
Error on startup (NoneType object >> no settings)

### ISSUE THREAD

**Issue by jrappen** [divmain/GitSavvy#673]
Opened Sublime with no open tabs.

```text
Traceback (most recent call last):
  File "git_savvy in ...\subl3\Data\Installed Packages\GitSavvy.sublime-package", line 14, in <lambda>
  File "common.util.view in ...\subl3\Data\Installed Packages\GitSavvy.sublime-package", line 66, in refresh_gitsavvy
AttributeError: 'NoneType' object has no attribute 'settings'
```

* Subl3 `Build 3136` x64 portable on Win 10 Pro x64
  * GitSavvy `v2.14.2`
* Git portable `2.12.2.windows.2`

**Comment by stoivo** [comment]
I don't have it error on my mac, but it is an easy fix.

**Comment by stoivo** [comment]
Without any proof, I think it is (this)[https://github.com/stoivo/GitSavvy/blob/1b98e9b50669f934a9a3940c6b1f53c104fc3879/git_savvy.py#L13-L14]
