### ISSUE TITLE
`git: cherrypick` is not working

### ISSUE THREAD

**Issue by randy3k** [divmain/GitSavvy#689]
```python
Traceback (most recent call last):
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/GitSavvy/core/commands/log.py", line 112, in on_branch_selection
    super().run_async(branch=self.all_branches[index])
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/GitSavvy/core/commands/log.py", line 29, in run_async
    lambda commit: self.do_action(commit, file_path=file_path)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/GitSavvy/core/ui_mixins/quick_panel.py", line 151, in show_log_panel
    lp.show()
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/GitSavvy/core/ui_mixins/quick_panel.py", line 195, in show
    self.load_next_batch()
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/GitSavvy/core/ui_mixins/quick_panel.py", line 177, in load_next_batch
    for item in itertools.islice(self.item_generator, self.limit):
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/GitSavvy/core/ui_mixins/quick_panel.py", line 167, in <genexpr>
    self.item_generator = (item for item in items)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/GitSavvy/core/git_mixins/history.py", line 72, in log_generator
    logs = self.log(limit=limit, skip=skip, **kwargs)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/GitSavvy/core/commands/cherry_pick.py", line 12, in log
    kwargs["start_end"] = ("", self._branch)
AttributeError: 'GsCherryPickCommand' object has no attribute '_branch'
```

**Comment by randy3k** [comment]
@asfaltboy I wanted to ask it for a long time. How do you add the `in progress` label automatically?

**Comment by asfaltboy** [comment]
To be honest I'm not entirely sure. It must be some app I authorized access to my Github account, that does this sort of automation... it's a bit of a nuisance really
