### ISSUE TITLE
Unable to cherry pick

### ISSUE THREAD

**Issue by allen-zeng** [divmain/GitSavvy#692]
This started happening recently. Whenever I go to cherry pick, nothing happens. The console prints the following:
> Traceback (most recent call last):
  File "core.commands.log in /Users/allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 112, in on_branch_selection
  File "core.commands.log in /Users/allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 29, in run_async
  File "core.ui_mixins.quick_panel in /Users/allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 151, in show_log_panel
  File "core.ui_mixins.quick_panel in /Users/allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 195, in show
  File "core.ui_mixins.quick_panel in /Users/allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 177, in load_next_batch
  File "core.ui_mixins.quick_panel in /Users/allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 167, in <genexpr>
  File "core.git_mixins.history in /Users/allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 72, in log_generator
  File "core.commands.cherry_pick in /Users/allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 12, in log
AttributeError: 'GsCherryPickCommand' object has no attribute '_branch'

The log reads:
```json
[
  {
    "stdout": "/Users/allen/Documents/Dev/<Redacted>\n", 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stdin": null, 
    "secounds": 0.008665800094604492, 
    "type": "git", 
    "stderr": ""
  }, 
  {
    "stdout": "/Users/allen/Documents/Dev/<Redacted>\n", 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stdin": null, 
    "secounds": 0.008189916610717773, 
    "type": "git", 
    "stderr": ""
  }, 
  {
    "stdout": "<See formatted output below>", 
    "command": [
      "branch", 
      "-a", 
      "-vv", 
      "--no-abbrev", 
      "--no-color", 
      null
    ], 
    "stdin": null, 
    "secounds": 0.015789031982421875, 
    "type": "git", 
    "stderr": ""
  }, 
  {
    "stdout": "", 
    "command": [
      "config", 
      "branch.backup.description"
    ], 
    "stdin": null, 
    "secounds": 0.00795602798461914, 
    "type": "git", 
    "stderr": ""
  }, 
  {
    "stdout": "", 
    "command": [
      "config", 
      "branch.develop.description"
    ], 
    "stdin": null, 
    "secounds": 0.008260011672973633, 
    "type": "git", 
    "stderr": ""
  }, 
  {
    "stdout": "", 
    "command": [
      "config", 
      "branch.newbranch.description"
    ], 
    "stdin": null, 
    "secounds": 0.00801992416381836, 
    "type": "git", 
    "stderr": ""
  }, 
  {
    "stdout": "  backup\n  develop\n* newbranch\n", 
    "command": [
      "branch", 
      "--no-color"
    ], 
    "stdin": null, 
    "secounds": 0.008919954299926758, 
    "type": "git", 
    "stderr": ""
  }, 
  {
    "stdout": "/Users/allen/Documents/Dev/<Redacted>\n", 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stdin": null, 
    "secounds": 0.006803989410400391, 
    "type": "git", 
    "stderr": ""
  }, 
  {
    "stdout": "/Users/allen/Documents/Dev/<Redacted>\n", 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stdin": null, 
    "secounds": 0.0077021121978759766, 
    "type": "git", 
    "stderr": ""
  }, 
  {
    "stdout": "/Users/allen/Documents/Dev/<Redacted>\n", 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stdin": null, 
    "secounds": 0.008243083953857422, 
    "type": "git", 
    "stderr": ""
  }
]
```

The most interesting part of the log reads like below (note the redacted SHAs are the exact lengths of them):
```
  backup                                 <Redacted SHA1 000000000000000000000000> <Redacted>
  develop                                <Redacted SHA2 000000000000000000000000> [remote1/develop] <Redacted>
* newbranch                              <Redacted SHA3 000000000000000000000000> [remote1/newbranch: ahead 1, behind 5] <Redacted>
  remotes/remote1/redacted               <Redacted SHA4 000000000000000000000000> Merge remote-tracking branch 'remote2/develop' into redacted
  remotes/remote1/develop                <Redacted SHA2 000000000000000000000000> <Redacted>
  remotes/remote1/newbranch              <Redacted SHA5 000000000000000000000000> <Redacted>
  remotes/remote1/redacted               <Redacted SHA6 000000000000000000000000> <Redacted>
  remotes/remote1/redacted               <Redacted SHA7 000000000000000000000000> <Redacted>
  remotes/remote1/redacted               <Redacted SHA8 000000000000000000000000> <Redacted>
  remotes/remote1/redacted               <Redacted SHA9 000000000000000000000000> <Redacted>
  remotes/remote2/HEAD                   -> remote2/develop
  remotes/remote2/redacted               <Redacted SHA10 00000000000000000000000> <Redacted>
  remotes/remote2/develop                <Redacted SHA11 00000000000000000000000> <Redacted>
  remotes/remote2/redacted               <Redacted SHA12 00000000000000000000000> <Redacted>
  remotes/remote2/redacted               <Redacted SHA13 00000000000000000000000> <Redacted>
  remotes/remote2/redacted               <Redacted SHA14 00000000000000000000000> <Redacted>
  remotes/remote2/redacted               <Redacted SHA15 00000000000000000000000> <Redacted>
  remotes/remote2/redacted               <Redacted SHA16 00000000000000000000000> <Redacted>
```

**Comment by randy3k** [comment]
It was just fixed
