### ISSUE TITLE
Something wrong with git push to existing branch

### ISSUE THREAD

**Issue by kiddick** [divmain/GitSavvy#756]
```
Traceback (most recent call last):
  File "core.commands.push in /home/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 100, in <lambda>
AttributeError: 'GsPushToBranchCommand' object has no attribute 'selected_remote'
Traceback (most recent call last):
  File "core.commands.push in /home/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 100, in <lambda>
AttributeError: 'GsPushToBranchCommand' object has no attribute 'selected_remote'
```

Btw everything is ok with manual pushing from console.

**Comment by randy3k** [comment]
I apologize, it is caused by a recent refactoring. Will fix soon.
