### ISSUE TITLE
Commands unavailable in command palette

### ISSUE THREAD

**Issue by gannicottb** [divmain/GitSavvy#940]
- Sublime Text version number: 3.0, build 3170
- Git version number: 2.4.2
- OS type and version: Mac OSX High Sierra, 10.13.3

Noticed that the usual commands for GitSavvy (status, push, etc) are unavailable in the command palette. Uninstalling and reinstalling the package has no effect, but the reinstall did yield the attached console output.

Console error output:
> reloading plugin GitSavvy.__init__
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /Users/brandong/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package
reloading plugin GitSavvy.git_savvy
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandong/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/git_savvy.py", line 41, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandong/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/gitlab/commands/__init__.py", line 1, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandong/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/gitlab/commands/open_on_remote.py", line 5, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandong/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/gitlab/gitlab.py", line 14, in <module>
ImportError: cannot import name FailedGitLabRequest

Let me know how else I can help troubleshoot.

**Comment by stoivo** [comment]
I see you have updated Sublime to lates release.
Have you tried to restart sublime. Maybe also the mac?

Never seen this error before.

**Comment by stoivo** [comment]
Yess!!!!! I am pro at fixing these issue.  :D  Glad we solved it
