### ISSUE TITLE
git_command.py utf-8 error

### ISSUE THREAD

**Issue by m-sostero** [divmain/GitSavvy#966]
I've started getting this error on Sublime Text 3176 (Portable Edition) with git 2.17.1 on Windows 7.

```
'utf-8' codec can't decode byte 0x8a in position 16: invalid start byte

Traceback (most recent call last):
  File "[...]Sublime\Data\Installed Packages\GitSavvy.sublime-package\core/git_command.py", line 215, in git
    stdout, stderr = self.decode_stdout(stdout), stderr.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 16: invalid start byte
```

The error appears on loading Sublime and prevents using GitSavvy. It was running until recently with no notable changes and updates.

**Comment by randy3k** [comment]
It seems that the error is thrown when STDERR is decoded.

**Comment by randy3k** [comment]
I have just pushed a branch [stderr](https://github.com/divmain/GitSavvy/tree/stderr). Could you give it a try? If it doesn't work, try playing the setting `fallback_encoding`.

**Comment by m-sostero** [comment]
This is what I get from the log
```json
[
  {
    "error": "'Please report this error to GitSavvy:\\n\\n\\'utf-8\\' codec can\\'t decode byte 0x8a in position 16: invalid start byte\\n\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\m.sostero\\\\Documents\\\\Sublime\\\\Data\\\\Installed Packages\\\\GitSavvy.sublime-package\\\\core/git_command.py\", line 215, in git\\n    stdout, stderr = self.decode_stdout(stdout), stderr.decode()\\nUnicodeDecodeError: \\'utf-8\\' codec can\\'t decode byte 0x8a in position 16: invalid start byte\\n'", 
    "type": "error"
  }, 
  {
    "seconds": 0.04679989814758301, 
    "stdin": null, 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stdout": [
      "\r\nC:\\Users\\m.sostero\\Documents>"
    ], 
    "stderr": "stderr was sent as binaries and we dont know the encoding, not utf-8", 
    "type": "git"
  }
]
```

**Comment by m-sostero** [comment]
From the `stderr` branch I enable logging and get this. Notice the byte sequence in my current locale (Windows, Italian):
```json
[
  {
    "seconds": 0.062400102615356445, 
    "type": "git", 
    "stdout": "\r\nC:\\Users\\m.sostero\\Documents\\Sublime\\Data\\Packages\\User>", 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stderr": "\"rev-parse\" non \u008a riconosciuto come comando interno o esterno,\r\n un programma eseguibile o un file batch.\r\n", 
    "stdin": null
  }
]
```

I guess the utf-8 error is because of the byte `\u008a` in stderr. 
stderr itself say he can't find `rev-parse`. 

This is a portable installation, so I may have to work around it.
However, it worked briefly yesterday when I started it.

**Comment by m-sostero** [comment]
Now the main message from GitSavvy on opening Sublime is"invalid directory name":

```
Please report this error to GitSavvy:

[WinError 267] Nome di directory non valido

Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
NotADirectoryError: [WinError 267] Nome di directory non valido

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m.sostero\Documents\Sublime\Data\Packages\GitSavvy\core\git_command.py", line 192, in git
    startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
NotADirectoryError: [WinError 267] Nome di directory non valido

```

**Comment by randy3k** [comment]
Beside the error msg, is it working?

**Comment by m-sostero** [comment]
No. I will check Sublime and GitSavvy logs to see what's happening.

**Comment by randy3k** [comment]
Is your directory on the sidebar not existing?

**Comment by Boomerml** [comment]
```
Please report this error to GitSavvy:

'utf-8' codec can't decode byte 0xca in position 284: invalid continuation byte

Traceback (most recent call last):
  File "C:\Users\Кирилл\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/git_command.py", line 215, in git
    stdout, stderr = self.decode_stdout(stdout), stderr.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 284: invalid continuation byte

```

**Comment by Boomerml** [comment]
I'm trying to make a commit

**Comment by Boomerml** [comment]
```
[
  {
    "type": "error", 
    "error": "'Please report this error to GitSavvy:\\n\\n\\'utf-8\\' codec can\\'t decode byte 0xca in position 284: invalid continuation byte\\n\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\\u041a\u0438\u0440\u0438\u043b\u043b\\\\AppData\\\\Roaming\\\\Sublime Text 3\\\\Installed Packages\\\\GitSavvy.sublime-package\\\\core/git_command.py\", line 215, in git\\n    stdout, stderr = self.decode_stdout(stdout), stderr.decode()\\nUnicodeDecodeError: \\'utf-8\\' codec can\\'t decode byte 0xca in position 284: invalid continuation byte\\n'"
  }, 
  {
    "command": [
      "commit", 
      "-q", 
      null, 
      null, 
      "-F", 
      "-"
    ], 
    "stdout": [
      ""
    ], 
    "stderr": "stderr was sent as binaries and we dont know the encoding, not utf-8", 
    "type": "git", 
    "seconds": 0.2389981746673584, 
    "stdin": [
      "first"
    ]
  }
]
```

**Comment by asfaltboy** [comment]
@Boomerml please try the latest version (the better logging `stderr` branch was already merged); you should be able to see the real error occurring on commit. Please open a new issue is there is still some problem in GitSavvy we can help resolve.
