### ISSUE TITLE
CMD+W no longer closes the "COMMIT" screen

### ISSUE THREAD

**Issue by ibc** [divmain/GitSavvy#995]
If you encounter a bug, please check for an open issue that already captures the problem you've run into.  If it doesn't exist yet, create it!

Please include the following information when filing a bug:

- Sublime Text version number: 3.1.1 Build 3176
- Git version number: 2.14.3
- OS type and version: OSX 10.13.6
- Console error output: none

- A description of the problem

Since latest version (sorry, not sure how to check which the version is, but it was upgraded today after restarting Sublime Text), once in the "COMMIT" screen, the tab cannot be closed by just pressing CMD+W. Instead, I must go to the tab and click on the "close" icon. This did not happen in previous versions in which the "COMMIT" screen could be closed via common CMD+W.

- Steps to reproduce, if possible

Just select some git changes, press "C" (so the "COMMIT" screen is opened) and, once in the "COMMIT" screen, press CMD+W. Nothing happens.

**Comment by randy3k** [comment]
Would you also include your `GitSavvy.sublime-settings`?

**Comment by ibc** [comment]
```json
{
	"git_path": "/usr/local/bin/git",
	"api_tokens": {
	    "github.com": "ec543d4fee0e50b7c88c846b0aa933663c6ced76"
	},
	"show_commit_diff": true,
	"show_panel_for": [
		"pull",
		"push"
	]
}
```

**Comment by randy3k** [comment]
There were some improvements related to the commit view in the last release. So it may be a result of the update.

Is there any error message in the console when you git `CMD+W`?

It may be possible that `CMD+W` is mapped by another package. Try running `sublime.log_commands(True)` in sublime console and check what command is being triggered when you git `CMD+W`..

**Comment by ibc** [comment]
Just `command: close`.

To clarify: I can perfectly close **any** other Sublime Text tab by pressing CMD+W, all the tabs but the "COMMIT" one.

**Comment by randy3k** [comment]
so the console shows `command: close` when you are pressing `CMD+W` in commit view, but the window was not closed and there is no error message?

**Comment by ibc** [comment]
Oh, yes, sorry, when in the "COMMIT" tab I press CMD+W, the console prints `command: gs_commit_view_close`. And nothing happens.

NOTE: If in that moment I click on the console view itself (so it gets the focus) and then CMD+W, then yes the "close dialog" is shown ("Do you want to save the changes you made to New file?"), which isn't very cool BTW...

NOTE 2: When going to `git status`, I've got en error when pressing CMD+W:

```
command: close
Traceback (most recent call last):
  File "/Users/ibc/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 166, in git
  File "/Users/ibc/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 421, in repo_path
RuntimeError: Window does not exist.

During handling of the above exception, another exception occurred (but this is unrelated and just happened once, not the next times I've done the same):

Traceback (most recent call last):
  File "/Users/ibc/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/common/ui.py", line 293, in run_async
  File "/Users/ibc/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/common/ui.py", line 103, in render
  File "/Users/ibc/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/common/ui.py", line 121, in _render_template
  File "/Users/ibc/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/common/ui.py", line 159, in get_keyed_content
  File "./python3.3/collections/__init__.py", line 56, in __init__
  File "./python3.3/collections/abc.py", line 578, in update
  File "/Users/ibc/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/common/ui.py", line 159, in <genexpr>
  File "/Users/ibc/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/interfaces/status.py", line 145, in render_branch_status
  File "/Users/ibc/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_mixins/active_branch.py", line 71, in get_branch_status
  File "/Users/ibc/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_mixins/active_branch.py", line 31, in _get_branch_status_components
  File "/Users/ibc/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 169, in git
GitSavvy.core.exceptions.GitSavvyError: Window does not exist.
```

**Comment by randy3k** [comment]
That’s odd....

**Comment by randy3k** [comment]
Would you restart Sublime Text and try again?

**Comment by ibc** [comment]
Sorry, didn't try that. It works now, and even the "close dialog" (when the commit is pending) is correct now.

I assume this issue can be closed (but take into account that it seems to require a double Sublime Text restart to work properly).

**Comment by randy3k** [comment]
Great.
